name: 🐛 Bug Report
description: Report a bug or issue with ProcessLens
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us diagnose and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe what happened and what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Open VS Code
        2. Run command '...'
        3. Click on '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened (include error messages, screenshots, etc.)
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: ProcessLens Version
      description: What version of ProcessLens are you using?
      placeholder: "0.1.1"
    validations:
      required: true

  - type: input
    id: vscode-version
    attributes:
      label: VS Code Version
      description: What version of VS Code are you using?
      placeholder: "1.85.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Windows
        - macOS
        - Linux
    validations:
      required: true

  - type: textarea
    id: console-logs
    attributes:
      label: Console Logs
      description: |
        If applicable, please include any error messages from:
        - VS Code Developer Console (Help > Toggle Developer Tools > Console)
        - ProcessLens Dashboard Console (if dashboard is open)
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (screenshots, related issues, etc.)

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to make sure this is not a duplicate
          required: true
        - label: I have included all the requested information above
          required: true
